// Define your game details
export const gameDetails = [
  { title: "ID", name: "id" },
  { title: "Provider", name: "companyName" },
  { title: "Provider Email Address", name: "companyEmail" },
  { title: "Game Name", name: "gameName" },
  { title: "Go Live Date", name: "goLiveDate" },
  { title: "Expiration Date", name: "expirationDate" },
  { title: "Certified Countries", name: "certifiedCountries" },
  { title: "Certified Countries With Different Live Date", name: "certifiedCountryCheck" },
  { title: "Certified Countries With Different Live Date and Exp Date", name: "multiLiveExpDate" },
  { title: "Country Certified File", name: "certifiedFiles" },
  { title: "Game Type", name: "gameType" },
  { title: "Video Slot", name: "vsHorizontal" },
  { title: "Game Theme", name: "gameTheme" },
  { title: "Currency", name: "currencyCode" },
  { title: "No. of RTP Variations", name: "rtp" },
  { title: "RTP Variation(s) in %", name: "rtpsVariation" },
  { title: "Short Game Description", name: "gameDescShort" },
  { title: "Long Game Description", name: "gameDescLong" },
  { title: "Game Special Features", name: "gameSpecialFeatures" },
  { title: "Number of Symbols to Trigger Feature/Bonus", name: "numberOfSymbolsTrigger" },
  { title: "Can Feature/Bonus be Retriggered?", name: "featureBonusRetriggered" },
  { title: "Number of Free Spins Awarded", name: "numberOfFreeSpinsAwarded" },
  { title: "Number of Jackpot Tiers", name: "numberOfJackpotTiers" },
  { title: "Auto-play Function?", name: "autoPlayFunction" },
  { title: "Technology", name: "technology" },
  { title: "Auto Detect Mobile", name: "autoDetectMobile" },
  { title: "Platforms", name: "platforms" },
  { title: "Volatility", name: "volatility" },
  { title: "Max Multiplier", name: "maxMultiplier" },
  { title: "Default Bet", name: "defaultBet" },
  { title: "Minimum Bet", name: "minimumBet" },
  { title: "Max Bet Small Operators", name: "maxBetSmallOperators" },
  { title: "Max Bet Big Operators", name: "maxBetBigOperators" },
  { title: "Hit Rate", name: "hitRate" },
  { title: "Pay Ways", name: "vsPayWays" },
  { title: "Demo Link", name: "demoLink" },
  { title: "Deep Link to Marketing Kit", name: "deepLink" },
  { title: "Marketing Bonus For Players  Allowed", name: "marketingBonus" },
  // { title: "Game Email", name: "gameEmail" },
  // { title: "Transaction Data Link", name: "transactionDataLink" },
  // { title: "Back Link", name: "backLink" },
  { title: "Game Status", name: "gameStatus" },
  { title: "Launch URL Format", name: "launchURLFormat" },
  { title: "Native Back To Lobby URL", name: "backToLobbyURL" },
  { title: "Native AddDeposit URL", name: "addDepositURL" },
  { title: "Dynamic Promotion Support", name: "dynamicPromotion" },
  { title: "Responsible-Gaming", name: "responsibleGaming" },
  { title: "Mini Games Supported", name: "miniGamesSupported" },
  { title: "Logos and Images", name: "logoOfGames" },
];

//ProviderProposalOptions
export const ProviderProposalOptions = [
  { title: "ID", name: "id" },
  { title: "Provider Name", name: "providerName" },
  { title: "Proposal Name", name: "proposalName" },
  { title: "Number of existing games in catalog", name: "NumberOfExistingGamesInCatalog" },
  { title: "Number of new games per year (approx)", name: "NumberOfNewGamesPerYear" },
  { title: "Included Countries", name: "includedCountries" },
  { title: "Local Licenses available in", name: "localLicenses" },
  { title: "Restricted Countries", name: "restrictedCountries" },
  { title: "Currency", name: "currency" },
  { title: "RevShare based on GGR or NGR", name: "revShareBased" },
  { title: "RevShare to Provider* in %", name: "revShareProvider" },
  { title: "Revshare tied to Game Type (in %)", name: "revShareTiedToGameType" },
  { title: "Revshare tied to Revenue tiers ", name: "revshareRevenueTiers" },
  { title: "Setup cost", name: "setUpCost" },
  { title: "Minimum Absolute Revshare Fee ", name: "minimumAbsoluteRevshareFee" },
  { title: "Grace Period for Minimum Absolute Fee", name: "gracePeriodforMinimumAbsoluteRevshareFee" },
  { title: "Branded Game surcharge in % ", name: "brandedGameSurchargeIn" },
  { title: "Bonuses and Promotions included", name: "bonusesAndPromotionsIncluded" },
];


//OperatorProposalOptions
export const OperatorProposalOptions = [
  { title: "ID", name: "id" },
  { title: "Proposal Name", name: "proposalName" },
  { title: "Number of new active user by monthly*", name: "numberOfMonthlyActiveUsers" },
  { title: "Number of offered games", name: "numberOfGamesOffered" },
  { title: "Restricted Countries", name: "restrictedCountries" },
  { title: "Number of brands", name: "numberOfBrands" },
  {
    title: "Revshare tied to Revenue tiers",
    name: "revshareRevenueTiers",
  },
  {
    title: "Number of new active user by monthly",
    name: "numberOfMonthlyActiveUsers",
  },
  { title: "Local Licenses available in", name: "localLicenses" },
  { title: "RevShare to Provider* in %", name: "revShareProvider" },
  { title: "iGamingDirectory.com Rank (last quarter)", name: "alexaRankInStrongestCountry" },
];


export const operatorUrl = [
  { url: "/", method: "all" },
  { url: "users", method: "read" },
  { url: "contracts", method: "all" },
  { url: "games", method: "no" },
  { url: "providers", method: "all" },
  { url: "externalProviderOperator", method: "all" },
  { url: "gameTheme", method: "read" },
  { url: "gameTracking", method: "no" },
  { url: "operatorProposal", method: "all" },
  { url: "operators", method: "all" },
  { url: "proposalTracking", method: "all" },
  { url: "providerOperator", method: "all" },
  { url: "providerProposal", method: "no" },
  { url: "reconciliation", method: "all" },
  { url: "user_provider_operator", method: "all" },
  { url: "scrappergames", method: "no" },
];
export const adminUrl = [ 
  { url: "/", method: "all" },
  { url: "users", method: "all" },
  { url: "contracts", method: "all" },
  { url: "games", method: "all" },
  { url: "providers", method: "all" },
  { url: "externalProviderOperator", method: "all" },
  { url: "gameTheme", method: "all" },
  { url: "gameTracking", method: "all" },
  { url: "operatorProposal", method: "all" },
  { url: "operators", method: "all" },
  { url: "proposalTracking", method: "all" },
  { url: "providerOperator", method: "all" },
  { url: "providerProposal", method: "all" },
  { url: "reconciliation", method: "all" },
  { url: "user_provider_operator", method: "all" },
  { url: "scrappergames", method: "all" },
];


export const providerUrl = [
  { url: "/", method: "all" },
  { url: "users", method: "read" },
  { url: "contracts", method: "all" },
  { url: "games", method: "all" },
  { url: "providers", method: "all" },
  { url: "externalProviderOperator", method: "all" },
  { url: "gameTheme", method: "read" },
  { url: "gameTracking", method: "all" },
  { url: "operatorProposal", method: "no" },
  { url: "operators", method: "all" },
  { url: "proposalTracking", method: "all" },
  { url: "providerOperator", method: "all" },
  { url: "providerProposal", method: "all" },
  { url: "reconciliation", method: "all" },
  { url: "user_provider_operator", method: "all" },
  { url: "scrappergames", method: "all" },
];






